version: '3.5'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=androidDB
  backend:
    build:
      context: .
    ports:
      - 8080:8080

    